git_host:
  system: crhanGit
  admin_uri: git@localhost:gitolite-admin
  base_path: /home/git/repositories/
  host: vm1.crhan.info
  git_user: git
  # port: 22

git:
  git_max_size: 5242800
  git_timeout: 10
